### ISSUE TITLE
Code on master not loading images on Chrome/Safari

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Codecademy/40Phaser#3]
This is all I get after pressing "Play Game" :(

![image](https://user-images.githubusercontent.com/3335181/55576724-f59e5180-56df-11e9-962c-e3baee626dc7.png)

**Comment by albertocamacho** [comment]
I'll take a look

**Comment by LinKCoding** [comment]
This might be specific to CORS (and loading the game on Chrome/Safari). Workaround being using a server to launch the game or using Firefox. 

In Phaser 2.4.4, it looks like this might've helped. https://phaser.io/docs/2.4.4/Phaser.Loader.html#crossOrigin 
Though I haven't tried it for Phaser 3

**Comment by LinKCoding** [comment]
also possibly relevant: https://photonstorm.github.io/phaser3-docs/Phaser.Loader.LoaderPlugin.html 
![image](https://user-images.githubusercontent.com/25854220/58124004-275d7000-7bdb-11e9-8c9f-ad994e9181c7.png)
