### ISSUE TITLE
Easter Egg to link to this repo

### ISSUE THREAD

**Issue by LinKCoding** [Codecademy/40Phaser#38]
I think an "invisible box/button" that links to this repo would be a nice to have.
Couple of ideas:
+ Add a new HTML button 
  + Have it in a corner and set to "visible: none"
+ Provide a title so it shows some intriguing text on hover.
+ Clicking on the button will open a new tab that links to this repo

**Comment by JoshuaKGoldberg** [comment]
Ah, this was fixed by #70.
