### ISSUE TITLE
Make game higher resolution

### ISSUE THREAD

**Issue by NikilXYZ** [Codecademy/40Phaser#82]
Right now because of the resolution, it look a bit illegit like a sidebar ad.

If there's some kind of way to use vector fonts or render the canvas at higher resolution, it would fit in better with the rest of the Codecademy site!

**Comment by JoshuaKGoldberg** [comment]
:wave: @NikilXYZ, thanks for posting an issue!

I'm not sure what you mean: are there specific pieces of the game that you're seeing as fuzzy?

**Comment by NikilXYZ** [comment]
yea like the text where you say "(P)lay or (B)uild your own game"

*NIKIL RAGAV** | WHARTON BUSINESS | PENN ELECTRICAL ENGINEERING*

CEO inventXYZ <https://www.inventxyz.com/>

832.910.9645

**Comment by JoshuaKGoldberg** [comment]
![Screenshot of the aforementioned (P)lay or (B)uild your own game text](https://user-images.githubusercontent.com/3335181/101969041-41f99e80-3bf0-11eb-961c-4510077d219f.png)

Interesting! This text is done with the native Phaser text renderer on top of a direct rectangle. Maybe there are font aliasing settings that should be changed? [`pixelArt`](https://phaser.io/examples/v3/view/game-config/pixel-art-mode) looks reasonable.

I suppose if it looks much better we could take in a pull request for that, but I'm not sold that that'd make a big improvement. The overall design of the game is pretty bare-bones (we made it in an internal hackathon and haven't invested much in it).

**Comment by NikilXYZ** [comment]
[image: image.png]

I think even the entire canvas window might be rendering at a lower
resolution for some reason

*NIKIL RAGAV** | WHARTON BUSINESS | PENN ELECTRICAL ENGINEERING*

CEO inventXYZ <https://www.inventxyz.com/>

832.910.9645

**Comment by JoshuaKGoldberg** [comment]
I'm going to go ahead and close this for housekeeping, since nobody's suggested anything concrete to change at the code level. If you have a suggestion for what to do to improve resolution, please do post here!
